config/routes.rb
Rails.application.routes.draw do
  resources :balloons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/balloon.rb
class Balloon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balloons_controller.rb
class BalloonsController < ApplicationController
  before_action :set_balloon, only: %i[ show edit update destroy ]

  # GET /balloons or /balloons.json
  def index
    @balloons = Balloon.all
  end

  # GET /balloons/1 or /balloons/1.json
  def show
  end

  # GET /balloons/new
  def new
    @balloon = Balloon.new
  end

  # GET /balloons/1/edit
  def edit
  end

  # POST /balloons or /balloons.json
  def create
    @balloon = Balloon.new(balloon_params)

    respond_to do |format|
      if @balloon.save
        format.html { redirect_to balloon_url(@balloon), notice: "Balloon was successfully created." }
        format.json { render :show, status: :created, location: @balloon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @balloon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balloons/1 or /balloons/1.json
  def update
    respond_to do |format|
      if @balloon.update(balloon_params)
        format.html { redirect_to balloon_url(@balloon), notice: "Balloon was successfully updated." }
        format.json { render :show, status: :ok, location: @balloon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @balloon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balloons/1 or /balloons/1.json
  def destroy
    @balloon.destroy

    respond_to do |format|
      format.html { redirect_to balloons_url, notice: "Balloon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balloon
      @balloon = Balloon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balloon_params
      params.fetch(:balloon, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balloons_helper.rb
module BalloonsHelper
end

app/views/balloons/_balloon.html.erb
<div id="<%= dom_id balloon %>">
</div>

app/views/balloons/_form.html.erb
<%= form_with(model: balloon) do |form| %>
  <% if balloon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(balloon.errors.count, "error") %> prohibited this balloon from being saved:</h2>

      <ul>
        <% balloon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/balloons/edit.html.erb
<h1>Editing balloon</h1>

<%= render "form", balloon: @balloon %>

<br>

<div>
  <%= link_to "Show this balloon", @balloon %> |
  <%= link_to "Back to balloons", balloons_path %>
</div>

app/views/balloons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Balloons</h1>

<div id="balloons">
  <% @balloons.each do |balloon| %>
    <%= render balloon %>
    <p>
      <%= link_to "Show this balloon", balloon %>
    </p>
  <% end %>
</div>

<%= link_to "New balloon", new_balloon_path %>

app/views/balloons/new.html.erb
<h1>New balloon</h1>

<%= render "form", balloon: @balloon %>

<br>

<div>
  <%= link_to "Back to balloons", balloons_path %>
</div>

app/views/balloons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @balloon %>

<div>
  <%= link_to "Edit this balloon", edit_balloon_path(@balloon) %> |
  <%= link_to "Back to balloons", balloons_path %>

  <%= button_to "Destroy this balloon", @balloon, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>